unilang_languages_controller:
    pattern: /lang_info
    defaults: { _controller:unilang.languages.controller:info }

unilang_languages_controller:
    pattern: /wikidirect
    defaults: { _controller:unilang.languages.controller:wikidirect }
