unilang_languages_controller:
    pattern: /lang_info
    defaults: { _controller:unilang.languages.controller:info }

unilang_languages_wikiredirect:
    pattern: /wikipedia
    defaults: { _controller:unilang.languages.wikiredirect:info }
