services:
    unilang.chat.listener:
        class: unilang\chat\event\main_listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
        tags:
            - { name: event.listener }
